### PR TITLE
Codesandboxblock plus

### PR DESCRIPTION
**Pull request by davidqqq**
TODO:
1. rename `Codesandboxblock plus`
2. fix closing </script> for selected code ranges
3. add css class to each block

To create an example in Sapper, create the following except metadata.yml:
- scatterplot
  - App.svelte
  - package.json
  - rollup.config.json
  - metadata.yml (generated)

then in .sveltex file:
```
<script>
import { onMount } from "svelte"
</script>

::: codesandboxplus ../../../../src/scatterplot/App.svelte some?props default 10-31,34-40
\`\`\`svelte
\`\`\`
:::
```

### CODE REVIEW

**Comment by atepoorthuis** [comment]
Good work! A few specific points to address:

- Code/test structure. Let's not co-opt the existing codesandbox example but create a second example dir next to it. I think this whole plug-in might ultimately be extracted to its own repo or live together with the Florence site instead, so better to keep things separate. While we're at it, let's create a separate test file for codesandbox related functionality.
- For line number ranges, consider adopting something like this to broaden the supported logic. https://www.npmjs.com/package/parse-numeric-range.
- No need to insert the import statement in the root script block - you're assuming that one even exists, which it might not. Instead, I think it's much simpler just to insert a `js exec` code block instead. The `execCodeBlocks` will take care of the rest automatically.
- Is there a specific reason to import only onMount? I don't think this is necessary and we can enforce all imported components are ssr compatible instead (by implementing their own onMount logic where necessary). 
- For now, let's get rid of the whole iframe to keep things simple. Instead we'll have something like:
```html
<div class="example-container">
    <div class="example-rendered">
        <!-- svelte component here -->
    </div>

    <div class="example-code">
        <!-- full contents of App.svelte -->
    </div>

    <div class="example-code-highlight">
        <!-- highlighted contents of App.svelte -->
    </div>

    <div class="example-csv-link">
        <a href="link/to/csb">Edit</a>
    </div>
</div>
```

**Comment by davidqqq** [comment]
I believe it's a better practice to be explicit about imports for keeping track of all modules used. Also there is a chance users might import `onMount` again. They will be baffled by a `onMount` has been declared error if they had not read documentation. For the rest of points, I will improve base on your suggestion.

**Comment by atepoorthuis** [comment]
> I believe it's a better practice to be explicit about imports for keeping track of all modules used.

Not sure if I understand this yet - can you explain in a bit more detail? It seems you're currently doing:

https://github.com/spatialnetworkslab/sveltex-unified/blob/ec87ea24f0017d5fa09e7a04154090e957521947/src/codeSandBoxUploadPlus.js#L102-L106

What I meant is, couldn't we just do a regular import statement instead?

> Also there is a chance users might import `onMount` again.

Currently `onMount` doesn't seem imported automatically. Do you mean the user should do that themselves?

**Comment by davidqqq** [comment]
>Not sure if I understand this yet - can you explain in a bit more detail? It seems you're currently doing:
If imports are made explicit, it allows users to know what modules are being imported for debugging etc.

>Currently onMount doesn't seem imported automatically. Do you mean the user should do that themselves? 
Yes the user needs to import `onMount` .

If `onMount` is automatically included. Then 
```
<script>
import { onMount } from 'svelte'

onMount(()=>{
 // load something over network
})

::: codesandboxplus ../../../../src/scatterplot/App.svelte some?props default 10-31,34-40
\`\`\`svelte
\`\`\`
:::
```
gives an `onMount` has been declared error.

**Pull request merged**
